name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install latest npm
        run: sudo npm install -g npm@
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Test
        run: npm test
        env:
          CI: true
